
package it.polimi.prova.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.2
 * Fri Sep 21 15:02:31 CEST 2012
 * Generated source version: 2.6.2
 */

@XmlRootElement(name = "localSearchResponse", namespace = "http://prova.polimi.it/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "localSearchResponse", namespace = "http://prova.polimi.it/")

public class LocalSearchResponse {

    @XmlElement(name = "return")
    private java.util.List<java.lang.String> _return;

    public java.util.List<java.lang.String> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<java.lang.String> new_return)  {
        this._return = new_return;
    }

}

