
package it.polimi.prova.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.2
 * Fri Sep 21 15:02:31 CEST 2012
 * Generated source version: 2.6.2
 */

@XmlRootElement(name = "publishPrize", namespace = "http://prova.polimi.it/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "publishPrize", namespace = "http://prova.polimi.it/", propOrder = {"arg0", "arg1"})

public class PublishPrize {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;
    @XmlElement(name = "arg1")
    private int arg1;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

    public int getArg1() {
        return this.arg1;
    }

    public void setArg1(int newArg1)  {
        this.arg1 = newArg1;
    }

}

