
package it.polimi.prova.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.2
 * Fri Sep 21 15:02:31 CEST 2012
 * Generated source version: 2.6.2
 */

@XmlRootElement(name = "resultOrderingResponse", namespace = "http://prova.polimi.it/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resultOrderingResponse", namespace = "http://prova.polimi.it/")

public class ResultOrderingResponse {


}

