
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package it.polimi.prova;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-09-18T10:35:30.443+02:00
 * Generated source version: 2.6.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "TestWebServiceService",
                      portName = "TestWebServicePort",
                      targetNamespace = "http://prova.polimi.it/",
                      wsdlLocation = "http://localhost:8080/WebServiceTest/services/TestWebServicePort?wsdl",
                      endpointInterface = "it.polimi.prova.TestWebServiceSEI")
                      
public class TestWebServiceSEIImpl implements TestWebServiceSEI {

    private static final Logger LOG = Logger.getLogger(TestWebServiceSEIImpl.class.getName());

    /* (non-Javadoc)
     * @see it.polimi.prova.TestWebServiceSEI#answer(java.lang.String  arg0 )*
     */
    public java.lang.String answer(java.lang.String arg0) { 
        LOG.info("Executing operation answer");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return1509359674";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see it.polimi.prova.TestWebServiceSEI#doSleep(int  arg0 )*
     */
    public void doSleep(int arg0) { 
        LOG.info("Executing operation doSleep");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
