package it.polimi.prova;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-09-18T10:35:30.473+02:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "TestWebServiceService", 
                  wsdlLocation = "http://localhost:8080/WebServiceTest/services/TestWebServicePort?wsdl",
                  targetNamespace = "http://prova.polimi.it/") 
public class TestWebServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://prova.polimi.it/", "TestWebServiceService");
    public final static QName TestWebServicePort = new QName("http://prova.polimi.it/", "TestWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/WebServiceTest/services/TestWebServicePort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TestWebServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/WebServiceTest/services/TestWebServicePort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TestWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TestWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns TestWebServiceSEI
     */
    @WebEndpoint(name = "TestWebServicePort")
    public TestWebServiceSEI getTestWebServicePort() {
        return super.getPort(TestWebServicePort, TestWebServiceSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestWebServiceSEI
     */
    @WebEndpoint(name = "TestWebServicePort")
    public TestWebServiceSEI getTestWebServicePort(WebServiceFeature... features) {
        return super.getPort(TestWebServicePort, TestWebServiceSEI.class, features);
    }

}
