
package it.polimi.prova;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-09-18T10:35:30.305+02:00
 * Generated source version: 2.6.2
 * 
 */
public final class TestWebServiceSEI_TestWebServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://prova.polimi.it/", "TestWebServiceService");

    private TestWebServiceSEI_TestWebServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TestWebServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TestWebServiceService ss = new TestWebServiceService(wsdlURL, SERVICE_NAME);
        TestWebServiceSEI port = ss.getTestWebServicePort();  
        
        {
        System.out.println("Invoking answer...");
        java.lang.String _answer_arg0 = "_answer_arg0-493850358";
        java.lang.String _answer__return = port.answer(_answer_arg0);
        System.out.println("answer.result=" + _answer__return);


        }
        {
        System.out.println("Invoking doSleep...");
        int _doSleep_arg0 = 1532548022;
        port.doSleep(_doSleep_arg0);


        }

        System.exit(0);
    }

}
