package it.polimi.prova;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-09-18T10:35:30.460+02:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://prova.polimi.it/", name = "TestWebServiceSEI")
@XmlSeeAlso({ObjectFactory.class})
public interface TestWebServiceSEI {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "answer", targetNamespace = "http://prova.polimi.it/", className = "it.polimi.prova.Answer")
    @WebMethod
    @ResponseWrapper(localName = "answerResponse", targetNamespace = "http://prova.polimi.it/", className = "it.polimi.prova.AnswerResponse")
    public java.lang.String answer(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @RequestWrapper(localName = "doSleep", targetNamespace = "http://prova.polimi.it/", className = "it.polimi.prova.DoSleep")
    @WebMethod
    @ResponseWrapper(localName = "doSleepResponse", targetNamespace = "http://prova.polimi.it/", className = "it.polimi.prova.DoSleepResponse")
    public void doSleep(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
